CREATE TABLE sql (
id bigint NOT NULL,
sessionrid text,
clientuid integer,
clientuser text,
clientname text,
clientip text,
serveruid integer,
serveruser text,
serverhid integer,
serverip text,
servername text,
serverappid integer,
eventtime bigint,
eventtype integer,
sessiontype integer,
sessionproto integer,
sessionversion text,
eventid bigint,
departmentid integer,
sqlprocesstime integer,
sqltype integer,
sqllen integer,
sqltext text,
affecttable text,
affecttables integer,
isautocmd integer,
sqlresult integer,
statuscode integer,
execresult text,
affectrows integer,
auditrows integer,
dbname text,
appname text,
loglevel integer,
action integer,
acl text,
acltag JSON,
nodeid text,
datekey date
) ENGINE = MergeTree
PARTITION BY toYYYYMM(datekey)
ORDER BY id